[server]
headless = true
port = $PORT
enableCORS = false

[global]
developmentMode = false

[packageManager]
systemPackages = [
    "tesseract-ocr",
    "libtesseract-dev",
    "libleptonica-dev",
    "tesseract-ocr-fra",
    "tesseract-ocr-eng",
    "tesseract-ocr-script-fra",
    "tesseract-ocr-script-latn"
]
